spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000

app:
  redis:
    enable: true
  bookmanager:
    base-url: http://localhost:8082
  cache:
    cacheType: redis
    cache-names:
      - databaseBooks
      - databaseBooksByName
      - databaseBooksById
      - databaseBookByAuthor
      - databaseBookByCategory
    caches:
      databaseBooks:
        expiry: 10m
      databaseBooksByName:
        expiry: 10m
      databaseBooksById:
        expiry: 10m
      databaseBookByAuthor:
        expiry: 10m
      databaseBookByCategory:
        expiry: 10m

